baseURL = '/'
languageCode = 'de-de'
title = 'Rezepte'
theme = 'PaperMod'

[taxonomies]
  cuisine = "cuisines"
  carb = "carbs"
  protein = "proteins"
  category = "categories"
  diet = "diets"
  method = "methods"

[outputFormats]
  [outputFormats.JSON]
    baseName = "index"
    mediaType = "application/json"
    isPlainText = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  page = ["HTML", "JSON"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Rezepte"
  Content = "Eine Sammlung meiner Lieblingsrezepte"

[[menu.main]]
  identifier = "recipes"
  name = "Rezepte"
  url = "/recipes/"
  weight = 10

[[menu.main]]
  identifier = "filter"
  name = "Filter"
  weight = 20

[[menu.main]]
  identifier = "categories"
  name = "Kategorien"
  url = "/categories/"
  parent = "filter"
  weight = 10

[[menu.main]]
  identifier = "cuisines"
  name = "Küche"
  url = "/cuisines/"
  parent = "filter"
  weight = 20

[[menu.main]]
  identifier = "proteins"
  name = "Proteine"
  url = "/proteins/"
  parent = "filter"
  weight = 30

[[menu.main]]
  identifier = "diets"
  name = "Ernährung"
  url = "/diets/"
  parent = "filter"
  weight = 40

[[menu.main]]
  identifier = "methods"
  name = "Methoden"
  url = "/methods/"
  parent = "filter"
  weight = 50

[[menu.main]]
  identifier = "carbs"
  name = "Kohlenhydrate"
  url = "/carbs/"
  parent = "filter"
  weight = 60

[[menu.main]]
  identifier = "search"
  name = "Suche"
  url = "/search/"
  weight = 30
