baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Recipe Collection'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Recipe Collection"
  Content = "A collection of favorite recipes"

[[menu.main]]
  identifier = "recipes"
  name = "Recipes"
  url = "/recipes/"
  weight = 10

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 30
