baseURL = '/'
languageCode = 'de-de'
title = 'Rezepte'
theme = 'PaperMod'

[taxonomies]
  cuisine = "cuisines"
  carb = "carbs"
  protein = "proteins"
  category = "categories"
  diet = "diets"
  method = "methods"

[outputFormats]
  [outputFormats.JSON]
    baseName = "index"
    mediaType = "application/json"
    isPlainText = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  page = ["HTML", "JSON"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Rezepte"
  Content = "Eine Sammlung meiner Lieblingsrezepte"

[[menu.main]]
  identifier = "recipes"
  name = "Rezepte"
  url = "/recipes/"
  weight = 10

[[menu.main]]
  identifier = "cuisines"
  name = "KÃ¼che"
  url = "/cuisines/"
  weight = 20

[[menu.main]]
  identifier = "categories"
  name = "Kategorien"
  url = "/categories/"
  weight = 30
